-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria
(
    id bigint NOT NULL,
    nomecategoria text
);

CREATE TABLE IF NOT EXISTS public.produto
(
    codprodu bigint NOT NULL,
    nomeprodu text,
    unidadeprodu text,
    quantidadeprodu double precision,
    precoprodu double precision,
    PRIMARY KEY (codprodu)
);

CREATE TABLE IF NOT EXISTS public.telefone
(
    id bigint NOT NULL,
    numero character varying(500),
    tipo character varying(500),
    datafinal character varying(500),
    usuario bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL,
    login text,
    senha text,
    nome text,
    telefone text,
    cep text,
    cidade text,
    fotobase64 text,
    fotobase64miniatura text,
    contenttypecurriculo text,
    ativo boolean,
    sexo text,
    quantidadeprodu double precision,
    precoprodu double precision,
    PRIMARY KEY (id)
);
END;